services:
  db:
    image: mysql:lts
    container_name: unibite
    environment:
      MYSQL_ROOT_PASSWORD: secretpassword
      MYSQL_DATABASE: unibite
      TZ: Europe/Athens
    ports:
      - "3306:3306"
    volumes:
      - unibite_mysql_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  unibite_mysql_data: